#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_sqlite = env_modules.Clone()

# Thirdparty source files
thirdparty_obj = []
thirdparty_root = "#thirdparty/sqlite3/"
thirdparty_include = thirdparty_root + "include/"
thirdparty_dir = "#thirdparty/sqlite3/src/"
thirdparty_sources = [
    "sqlite3.c",
]


thirdparty_sources = [thirdparty_dir + src for src in thirdparty_sources]
env_sqlite.Prepend(CPPPATH=[thirdparty_include])


env_thirdparty = env_sqlite.Clone()
env_thirdparty.disable_warnings()

env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)

env.modules_sources += thirdparty_obj

# Godot source files

module_obj = []

env_sqlite.add_source_files(module_obj, "*.cpp")
env_sqlite.add_source_files(module_obj, "*.c")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
