#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_mediation = env_modules.Clone()

# Godot source files
env_mediation.add_source_files(env.modules_sources, "*.cpp")
if env["platform"] == "android":
    env_mediation.add_source_files(env.modules_sources, "android/*.cpp")

if env.editor_build:
    env_mediation.add_source_files(env.modules_sources, "editor/*.cpp")